
spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://localhost:8900
  sleuth:
    sampler:
      percintage: 1.0
server:
  port: 8901
eureka:
  instance: #此配置建议只试用开发和测试环境
    lease-renewal-interval-in-seconds: 2    #心跳间隔时间,默认是30秒
    lease-expiration-duration-in-seconds: 6 #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
